[package]
name = "conlang"
version = "0.1.0"
edition = "2024"
authors = ["Travis Gockel <travis@gockelhut.com>"]
license = "Apache-2.0"
keywords = ["conlang"]
categories = ["command-line-utilities", "text-processing"]
description = "Construct languages from phonetics, to orthography, to grammar, to lexicon, to completion."

[dependencies]
anyhow = "^1.0.71"
aws-config = { version = "^1.6.3", optional = true }
aws-sdk-polly = { version = "^1.74.0", optional = true }
bytes = "1.4.0"
clap = { version = "^4.3.1", features = ["derive"] }
cpal = { version = "^0.15.3", optional = true }
itertools = "^0.11.0"
rand = "^0.8.5"
smallvec = "^1.10.0"
thiserror = "^1.0.43"
tokio = { version = "^1.28.2", features = ["rt-multi-thread", "macros", "fs", "time"] }

[lib]

[[bin]]
name = "conlang"

[features]
default = ["pronounce"]
pronounce = ["dep:aws-config", "dep:aws-sdk-polly", "dep:cpal"]

# Compile dependencies with optimization
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
